### ISSUE TITLE
frameworks not found after pod install

### ISSUE THREAD

**Issue by atom2ueki** [segment-integrations/analytics-ios-integration-google-analytics#15]
I'm using swift 3 with xcode8, and base on #3 , I've done the patch to my cocoapods, after `pod install`, it shows me successful, but under pod/products, my libraries inside pods all red, cannot find the files, if I remove this lib config from podfile, it works.

**Comment by f2prateek** [comment]
Patching cocoapods is not recommended. This was the ideal solution https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3#issuecomment-205463875.

As of https://github.com/segment-integrations/analytics-ios-integration-google-analytics/pull/14, you can do:

```
pod  'GoogleAnalytics'
pod 'Segment-GoogleAnalytics/StaticLibWorkaround'
```

**Comment by atom2ueki** [comment]
@f2prateek it's not working, because Segment-GoogleAnalytics/StaticLibWorkaround is empty and all the frameworks under products folder also unable to link

**Comment by ladanazita** [comment]
@atom2ueki  Are you manually copying the integration code into your project? Here is a complete example app with the workaround: https://github.com/segmentio/TestAppSwiftUseFrameworksStaticLib

**Comment by Douvi** [comment]
The branch `static-lib-workaround` does not exist anymore... Guys come on this issue have been here for a long time, can you please do the right thing `Segment` to fix this issue!!!

**Comment by f2prateek** [comment]
@douvi see https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/15#issuecomment-259402236
