### ISSUE TITLE
impossible to import your lib with swift 3.0

### ISSUE THREAD

**Issue by Douvi** [segment-integrations/analytics-ios-integration-google-analytics#20]
```
# Uncomment this line to define a global platform for your project
swift_version = "3.0"
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

def libs
     ...
     pod 'Analytics', '~> 3.6.5'
     pod 'Segment-GoogleAnalytics', '1.1.6'
     ...
end
```

Error
```
[!] The 'Pods-panda' target has transitive dependencies that include static binaries: (/Users/xxx/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a and /Users/xxx/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a)
```

**Comment by ladanazita** [comment]
@Douvi Thanks for writing in here!

This is a known issue and we have a work around outlined [here](https://segment.com/docs/destinations/google-analytics/#target-has-transitive-dependencies-that-include-static-binaries). Hope this helps, let me know if you have any further questions!

**Comment by ladanazita** [comment]
Sorry @Douvi , I just realized that documentation is out of date. We have a subspec [here](https://github.com/segment-integrations/analytics-ios-integration-google-analytics/blob/master/Segment-GoogleAnalytics.podspec#L38).

With the StaticLibWorkaround workaround,  the integration files will not be present. You will have to manually add in the files to the main project.
