### ISSUE TITLE
Swift: GoogleAnalytics lib in two locations 

### ISSUE THREAD

**Issue by dmorrow** [segment-integrations/analytics-ios-integration-google-analytics#22]
I am getting a number of errors regarding GA lib classes

Class GAIUtil is implemented in both /Users/***/Library/Developer/CoreSimulator/Devices/81FFAA9C-B351-4EA9-91D8-F52C91C2CE07/data/Containers/Bundle/Application/07CD5C2E-B70D-4CCC-9761-7CCAEF3FBD52/{app_name}.app/Frameworks/Segment_GoogleAnalytics.framework/Segment_GoogleAnalytics (0x10ee8bb90) and /Users/***/Library/Developer/CoreSimulator/Devices/81FFAA9C-B351-4EA9-91D8-F52C91C2CE07/data/Containers/Bundle/Application/07CD5C2E-B70D-4CCC-9761-7CCAEF3FBD52/{app_name}.app/{app_name} (0x10b61a5b0). One of the two will be used. Which one is undefined.

I am using Swift, which means I currently have the following in my PodFile to enable static libs

    post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
                if config.build_settings['PRODUCT_NAME'] == "Segment_GoogleAnalytics"
                config.build_settings['LIBRARY_SEARCH_PATHS'] = ["$(inherited)", "$(PODS_ROOT)/GoogleAnalytics/Libraries", "$(PODS_ROOT)/GoogleIDFASupport/Libraries"]
                config.build_settings['OTHER_LDFLAGS'] = %Q{-weak_framework "CoreData" -weak_framework "SystemConfiguration" -l"z" -l"sqlite3" -l"sqlite3.0" -l"GoogleAnalytics"}
            end
        end
    end
    end

**Comment by ladanazita** [comment]
Hi @dmorrow 

I apologize for the delay here. 

I believe the issue here is the way GA is served as a static lib, you can't rely on it this way. Could you provide the full error here if this is the issue? If it is too complex, you can shoot a support ticket to segment.com/contact with the entire stacktrace.

Thanks,
Ladan
