### ISSUE TITLE
Add Carthage/Framework support

### ISSUE THREAD

**Issue by jPaolantonio** [segment-integrations/analytics-ios-integration-google-analytics#5]
I am not currently able to implement this into our current Segment implementation due to the fact that Carthage is not supported. We would need to build as a framework to support this.

For example, https://github.com/segment-integrations/analytics-ios-integration-mixpanel, builds as a framework and supports Carthage.

**Comment by CoolHandLuke88** [comment]
Any Time frame on Carthage Support?

**Comment by hankim813** [comment]
@segment-integrations/mobile

**Comment by dmorrow** [comment]
Is there a fix for this?

**Comment by ladanazita** [comment]
@dmorrow Sorry about this, it wasn't tracked properly internally. Give me a moment to scope out this work and I will update here.

**Comment by ladanazita** [comment]
@dmorrow I'm having trouble finding documentation to see if Google Analytics supports Carthage, can you provide this information?

My college Prateek also commented on a work around in [this issue](https://github.com/segment-integrations/analytics-ios-integration-flurry/issues/7#issuecomment-259670662).

Generally speaking, our internal efforts will be focused on moving away from the GA SDK towards supporting Firebase. From the [GA docs](https://developers.google.com/analytics/devguides/collection/firebase/ios/) they mention that they are now recommending the Firebase SDK to track iOS apps in Google Analytics over the Google Analytics Services SDK for iOS.

Ideally, if you can provide documentation on GA Firebase supporting Carthage, I will look into adding that support when I attend to building out the [Firebase SDK](https://github.com/segment-integrations/analytics-ios-integration-firebase) (we currently have one but we are in the process of updating it as it is a major version behind).

**Comment by dmorrow** [comment]
@ladanazita Thanks for the indepth response.  I don't believe the GA lib supports Carthage.  They were all in on Cocoapods.  I've manually added those static libraries, but it would be great to not have to manually add this integration as well.  I will look into Firebase as well.

**Comment by ladanazita** [comment]
@dmorrow Sounds good. I'm going to close this out and consider the workaround provided [here](https://github.com/segment-integrations/analytics-ios-integration-flurry/issues/7#issuecomment-259670662) as the current solution until GA supports Carthage. 

Until then, this is the best course to integrate GA + Segment + Carthage. If you find any further info that changes this, feel free to open this up again.
